#!/usr/bin/expect -f

set timeout 30
set host "82.97.253.158"
set user "root"
set password "frGyWb_kF#651v"
set project_path "/var/www/kanban.24task.ru"

spawn ssh $user@$host
expect {
    "yes/no" { send "yes\r"; exp_continue }
    "assword:" { send "$password\r" }
}

expect "#"
send "cd $project_path\r"
expect "#"
send "git status\r"
expect "#"
send "grep -n \"isPublic\" prisma/schema.prisma\r"
expect "#"
send "exit\r"
expect eof
