#!/usr/bin/expect -f

set timeout 30
set host "82.97.253.158"
set user "root"
set password "frGyWb_kF#651v"
set project_path "/var/www/kanban.24task.ru"

spawn ssh $user@$host
expect {
    "yes/no" { send "yes\r"; exp_continue }
    "assword:" { send "$password\r" }
}

expect "#"
send "pm2 list\r"
expect "#"
send "pm2 logs kanban-server --lines 20 --nostream\r"
expect "#"
send "exit\r"
expect eof
