#!/usr/bin/expect -f

set timeout 300
set host "82.97.253.158"
set user "root"
set password "frGyWb_kF#651v"
set project_path "/var/www/kanban.24task.ru"

spawn ssh $user@$host
expect {
    "yes/no" { send "yes\r"; exp_continue }
    "assword:" { send "$password\r" }
}

expect "#"
send "cd $project_path\r"
expect "#"
send "pm2 stop all\r"
expect "#"
send "rm -rf node_modules/.prisma\r"
expect "#"
send "npx prisma generate\r"
expect "#"
send "pm2 start all\r"
expect "#"
send "exit\r"
expect eof
